---
title: "Clases"
output: html_document
---
  
#### 1. 17/8

* [Presentación de la materia](https://github.com/guillermosolovey/laboratoriodedatos2021-2C/blob/master/docs/NotebooksTeoricas/Presentacion.pdf) | [Video de la clase](https://youtu.be/xeuQD_5NAEY) | extra: [Qué son los datos](https://youtube.com/playlist?list=PLN2e9R_DoC0SfT6Pnr2umyTw2hL-EVWPT)
* Instalación de R y RStudio: Para instalar R, sigan [este link](http://mirror.fcaglp.unlp.edu.ar/CRAN/) seleccionando su sistema operativo. Luego descarguen RStudio (versión gratuita) siguiendo [este link](https://www.rstudio.com/products/rstudio/download/#download). Si surge algún problema con esto, lo resolvemos en la clase. 
* Precalentamiento: [Video](https://youtube.com/playlist?list=PLq-WhOVzhK9yqiDESHs1x4zjUCDtQtWtp) | [Notebook](./NotebooksTeoricas/HelloR/notebook_HelloR.nb.html)
* Precalentamiento: [TP-0](./TrabajosPracticos/HelloR/ejercicios_HelloR.nb.html)

#### 2. 19/8

* Intro a estadistica descriptiva y visualización: [Videos, ver del 1-8](https://youtube.com/playlist?list=PLq-WhOVzhK9xNqZSIaq8-f1MTKmRswpF7) | [Notebook](./NotebooksTeoricas/Estadistica_Descriptiva/notebook_estadistica_descriptiva.nb.html) | [datos](./NotebooksTeoricas/Estadistica_Descriptiva/ar_properties.csv)
    
* Intro a estadistica descriptiva y visualización: [TP-1](./TrabajosPracticos/Temperaturas/temperatura_ejercicios.nb.html) | [datos](./TrabajosPracticos/Temperaturas/historico_temperaturas.csv)


####  3. 24/8

* Intro a estadistica descriptiva y visualización: [Videos, ver del 9-12](https://youtube.com/playlist?list=PLq-WhOVzhK9xNqZSIaq8-f1MTKmRswpF7) | [Notebook](./NotebooksTeoricas/Estadistica_Descriptiva/notebook_estadistica_descriptiva.nb.html) | [datos](./NotebooksTeoricas/Estadistica_Descriptiva/ar_properties.csv)
    
* Seguimos con intro a estadistica descriptiva y visualización: [TP-1](./TrabajosPracticos/Temperaturas/temperatura_ejercicios.nb.html) | [datos](./TrabajosPracticos/Temperaturas/historico_temperaturas.csv)

* [Fragmento de la clase sync](https://youtu.be/OJ9gP30TwtE)

#### 4. 26/8

* Intro a estadistica descriptiva y visualización: [Videos, ver del 13-16](https://youtube.com/playlist?list=PLq-WhOVzhK9xNqZSIaq8-f1MTKmRswpF7) | [Notebook](./NotebooksTeoricas/Estadistica_Descriptiva/notebook_estadistica_descriptiva.nb.html) | [datos](./NotebooksTeoricas/Estadistica_Descriptiva/ar_properties.csv)
    
* Seguimos con intro a estadistica descriptiva y visualización: [TP-1](./TrabajosPracticos/Temperaturas/temperatura_ejercicios.nb.html) | [datos](./TrabajosPracticos/Temperaturas/historico_temperaturas.csv) |  [TP-2](./TrabajosPracticos/Properarti_EstadisticaDescriptiva/properati_ejercicios.nb.html)

* Grabamos la resolución del TP1 que hicimos en clase. [video](https://youtu.be/c8t_yHLQgp4) | [notebook](./TrabajosPracticos/Temperaturas/temperaturas_ejercicio_resuelto.html)

#### 5. 31/8

* TP-2: re-explorando los datos de Properati. [notebook](./TrabajosPracticos/Properarti_EstadisticaDescriptiva/properati_ejercicios.nb.html) | [datos](./NotebooksTeoricas/Estadistica_Descriptiva/ar_properties.csv)

* Grabamos la puesta en común de la primera parte del TP 2. [video](https://youtu.be/hucTkW-OrvA)

#### 6. 2/9

* Análisis de Precios por Metro Cuadrado de CABA con Properati. [videos](https://youtube.com/playlist?list=PLN2e9R_DoC0RQu0ppINT_wyJY070V2zTr) | [notebook](./NotebooksTeoricas/Espacial_Properati/EDA-Precios-por-Metro-Cuadrado-de-CABA-con-Properatti.html)
* TP-2: re-explorando los datos de Properati. [notebook](./TrabajosPracticos/Properarti_EstadisticaDescriptiva/properati_ejercicios.nb.html) | [datos](./NotebooksTeoricas/Estadistica_Descriptiva/ar_properties.csv)


#### 7. 7/9

* Solución TP-2: [Video, parte1](https://youtu.be/JzoKhBOGFJk) | [Video, parte2](https://youtu.be/Kyr0WjVpgP4) | [script-p1](./TrabajosPracticos/Properati_resuelto/TP2-parte1.R) | [script-p2](./TrabajosPracticos/Properati_resuelto/TP2-parte2.R)
* Datos no estructurados. [Notebook](./NotebooksTeoricas/No_Estructurados_APIs/notebook_NS_apis.nb.html) | [Videos](https://youtube.com/playlist?list=PLmKafz8lJ_AXM7uxhasLR665ZqWlpC6RD)
* Comentarios sobre el TP de datos no estructurados: [Video](https://youtu.be/-XhcaSOGxXM)

#### 8. 9/9

* Esta clase vamos a dedicarla completamente a primera parte de la la guía de datos no estructurados (es decir, no a la parte de APIs). [Notebook](./NotebooksTeoricas/No_Estructurados_APIs/notebook_NS_apis.nb.html)  | [Videos](https://youtube.com/playlist?list=PLmKafz8lJ_AXM7uxhasLR665ZqWlpC6RD). Desde ya, el quiera seguir adelante con APIs ya está todo el material disponible para que lo hagan.
* Puesta en común de la primera parte del TP de datos no estructurados [Video](https://youtu.be/0jnWDETakVc)

#### 9. 11/9

* En la clase se resolvieron ejercicios de la scrapeo, primera parte de la guia de datos no estructurados

#### 10. 14/9

* APIs [Notebook](./NotebooksTeoricas/No_Estructurados_APIs/notebook_NS_apis.nb.html)  | [Videos](https://youtube.com/playlist?list=PLmKafz8lJ_AXM7uxhasLR665ZqWlpC6RD).
* Ejercicios de APIs. 

#### 11. 16/9

* En la clase se resolvieron ejercicios de APIs, segunda parte de la guia de datos no estructurados. Puesta en común: [video](https://youtu.be/jzwiAXzeRus)

#### 21/9 (día de la primavera, no hay clases)

#### 23/9 

* Visualización de datos. [4 videos](https://youtube.com/playlist?list=PLoRRdiqaH8sGK7H3vSaCcm5Aamg1gPfpp) | [Slides](https://docs.google.com/presentation/d/1yRIUasD-uEYOar0LAEFR_rD5Du3k4lFzU1M5mrfFXDQ/edit?usp=sharing)
* Ejercicios de visualización de datos, [parte 1](./TrabajosPracticos/Visualizacion1/TP4-Visualizacion.nb.html)


#### 28/9 

* Transformando datos con dplyr. [video](https://youtu.be/7kthnDAo9Vg) | [Slides](https://docs.google.com/presentation/d/1301HTmQV5mb11dXVyoo5KeRdu-HtuMOx88MtKN5zedI/edit?usp=sharing)
* Ejercicios de transformación de datos con dplyr. [TP](./TrabajosPracticos/Tidyverse2/TP-dplyr.nb.html)
* Ejercicios de transformación y visualización con tidyverse. [TP](./TrabajosPracticos/Tidyverse3/TP-tidy.html)
* Puesta en común. [Video](https://youtu.be/Gqbu-9fyt3o)


#### 30/9 

* Puesta en común de los TP de tidyverse. [Video](https://youtu.be/cYe5YM-f2T8)
* Qué hace un cientíico de datos? [Video](https://youtu.be/cYe5YM-f2T8?t=2150)


#### 5/10 

* Un pequeño vistazo a grafos [Notebook](./NotebooksTeoricas/Grafos/notebook_grafos.nb.html) | [Video](https://youtube.com/playlist?list=PLq-WhOVzhK9zNcO-QaOWWY18c-e_QVuwq)
* Resolución Ej 2 del [TP-3](./TrabajosPracticos/Visualizacion1/TP4-Visualizacion.nb.html) + discusión sobre
la paradoja de Simpson: [Video](https://youtu.be/3ygLXop_Nqc)



#### 7/10 

* [Comentarios sobre grafos](https://youtu.be/hDJGNjWC3Iw)
* Analisis exploratorio de los precios por metro cuadrdo de departamentos en CABA, con la base de Properati VERSION ELEGANTE: [Notebook](./NotebooksTeoricas/Espacial_Properati_v2/EDA_Properati_v2.html) | [Video-parte1](https://youtu.be/QPnWb5IUZIs) | [Video-parte2](https://youtu.be/n4LlZoWcrbE) | [Video-parte3](https://youtu.be/s2FaiaH9h30)


#### 12/10 

* Manejo de textos: [Notebook](./NotebooksTeoricas/Textos/manejo_textos.html)

* Material adicional: otra forma de ver los datos espaciales de Properati 
(VERSIÓN ELEGANTE 2): [Notebook](./NotebooksTeoricas/Espacial_Properati_v3/EDA_Properati_v3.html) | [Video-parte1](https://youtu.be/t30wAtJAeRc) | [Video-parte2](https://youtu.be/A4zOvXpZOeo) | [Video-parte3](https://youtu.be/SVwW6DfpWLc)

#### 14/10 al 2/11

* Trabajo Práctico. [enunciado]()

* Charlas invitadas de científicos de datos.

#### 4/11

* Modelado de datos:
- [Videos](https://youtube.com/playlist?list=PLN2e9R_DoC0THQgbage3DkS_7tCsqTd-3)
- [Apunte](./NotebooksTeoricas/Modelado/Modelado_con_Regresion_Lineal_Multiple_Final.pdf)
- Notebook: [html](./NotebooksTeoricas/Modelado/Modelado_de_Precios_5.nb.html) | [Rmd](./NotebooksTeoricas/Modelado/Modelado_de_Precios_5.Rmd)
- [TP](./NotebooksTeoricas/Modelado/TP_Modelado_de_Datos.pdf)


