---
title: "Programa"
output: html_document
---

### Contenidos

1. Obtención y organización de datos. Procesamiento de datos no estructurados. 
Interacción con páginas web y con APIs. Formatos de datos.
2. Herramientas para la visualización de datos: distintos tipos de figuras y
lineamientos generales para comunicar información basada en datos.
3. Visualización de datos como herramienta exploratoria antes del
desarrollo de modelos y aprendizaje estadísticos. Análisis exploratorio de datos.
4. Introdución al modelado. Modelos predictivos versus modelos
explicativos. Distinción entre modelos univariados y multivariados, y modelos
paramétricos y no-paramétricos.
5. Herramientas de validación de un modelo. Muestras de testeo y
entrenamiento.Métricas y métodos para la evaluación de algoritmos y modelos
estadísticos.
6. Métodos de Clasificación: K-NN, árboles de decisión.
7. Técnicas de aprendizaje no supervisado: k-means, clustering jerárquico.

### Bibliografía
Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy,
transform, visualize, and model data. O'Reilly Media, Inc. [En español](https://es.r4ds.hadley.nz/)

